---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.5.1"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.5.1 - Cleanup: Remove broken browser auto-reload feature
  - REMOVED: Browser auto-reload on cache version change (was checking wrong version, never worked)
  - REMOVED: CacheDataVersion from API response (only supported the broken feature)
  - Simplifies codebase by removing non-functional code
  - Eager loading (v0.9.5.0) still works: cache refresh auto-populates Jellyfin database
