---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.16"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.16 - Performance Improvements and Cache Enhancements
  - PERFORMANCE: Series lists now cached per category, eliminating redundant API calls in flat view
  - FEATURE: Automatic browser cache invalidation when server cache changes
  - FEATURE: Configuration validation warns if series visibility enabled but no selections made
  - ENHANCEMENT: Cache status API now includes CacheDataVersion for tracking
  - IMPROVEMENT: UI automatically reloads when cache version changes (no more manual refresh needed)
  - Fixes issue where GetAllSeriesFlattened returned 0 series from cached categories
