---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.10"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.10 - Clear Cache Can Now Stop Refresh
  - IMPROVED: Clear Cache button now cancels running refresh instead of being disabled
  - No more waiting 50+ minutes for refresh to complete before clearing cache
  - Shows appropriate warning when clearing will stop an active refresh
  - FIXED: Unicode pipe tag parsing regex (from v0.9.4.9)
