---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.7"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.7 - Caching Toggle & Bug Fixes
  - NEW: Enable/disable caching toggle - Cache UI only shown when caching is enabled for cleaner interface
  - FIXED: Plugin preventing Jellyfin from starting when credentials not configured
  - FIXED: Refresh button not starting cache refresh - Background task was cancelled when HTTP request completed
  - FIXED: Clear Cache button showing 'Clearing' forever - Improved error handling in button handlers
  - FIXED: Episodes not showing after changing refresh frequency - Cache now only invalidates when relevant settings change
  - FIXED: Memory leak from orphaned cache entries - Added 24-hour safety expiration
