---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.15"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.15 - Enhanced Logging and Episode Display Fix (VERIFIED WORKING)
  - FIXED: Episodes now display correctly in all series
  - Added missing SeriesName and ImageUrl fields to episode metadata
  - Enhanced logging in GetAllSeriesFlattened for better diagnostics
  - Added error handling for category processing
  - Diagnostic logging helps troubleshoot caching and display issues
  - NOTE: Browser hard refresh (Ctrl+Shift+R/Cmd+Shift+R) may be needed after category changes
